/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/MmimBNV7IyG
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/
import { AvatarImage, AvatarFallback, Avatar } from "@/components/ui/avatar"
import Link from "next/link"
import { JSX, SVGProps } from "react"
import { PiTelegramLogoBold } from "react-icons/pi";
import { HoverBelka } from "./hover";
import { HoverGranit } from "./hoverGranit";
import Projects from "./projects";
import { MapPin } from "lucide-react";

export function Info() {
  return (
    <>
    <div className="max-w-4xl mx-auto p-8">
      <header className=" flex-col items-center mb-12">
        <Avatar className="mb-4 w-16 h-16">
          <AvatarImage alt="Artem Sharipov" src="/artem.jpeg" />
          <AvatarFallback>AK</AvatarFallback>
        </Avatar>
        <h1 className="text-2xl font-bold">Artem Sharipov</h1>
        <p className="text-md">Python Engineer & Web Developer</p>
        <MapPin className="mr-2 h-4 w-4 opacity-70" />{"Toronto, On"}
        <div className="flex space-x-4 mt-4">
          <Link href={'https://t.me/sharipovartem'}><PiTelegramLogoBold className="h-6 w-6"></PiTelegramLogoBold></Link>
          <Link href={'https://github.com/sharipovartem'}><GithubIcon className="h-6 w-6" /></Link>
          <Link href={'https://www.linkedin.com/in/artemsharipov/'}><LinkedinIcon className="h-6 w-6" /></Link>
        </div>
      </header>
      <nav className=" justify-center space-x-6 border-b pb-4 mb-8">
        <a className="text-sm font-semibold" href="#">
          About
        </a>
        <a className="text-sm font-semibold" href="#projects">
          Projects
        </a>
      </nav>
      <section className="mb-12">
        <p className="mb-8">
          Software engineer focusing on Python development, data analysis, and effective project management.
        </p>
        <h2 className="text-2xl font-bold mb-4">Experience</h2>
        
        <div className="mb-6">
          <h3 className="font-semibold">
            Software Engineer <span className="text-sm font-normal">(Jan 2022 — July 2023)</span>
          </h3>
          <Link href={"https://belka.ai/en"}><HoverBelka /></Link>
        </div>
        <div className="mb-6">
          
          <h3 className="font-semibold">Full-Stack Developer<span className="text-sm font-normal">(Oct 2020 — Dec 2021)</span>
          </h3>
          <HoverGranit />
        </div>
        <h2 className="text-2xl font-bold mb-4 " id="projects">Projects</h2>
        < Projects />
      </section>
      <footer className="text-center">
        <p>© 2024 - Artem Sharipov</p>
      </footer>
    </div>
    

    </>
  )
}






function GithubIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M15 22v-4a4.8 4.8 0 0 0-1-3.5c3 0 6-2 6-5.5.08-1.25-.27-2.48-1-3.5.28-1.15.28-2.35 0-3.5 0 0-1 0-3 1.5-2.64-.5-5.36-.5-8 0C6 2 5 2 5 2c-.3 1.15-.3 2.35 0 3.5A5.403 5.403 0 0 0 4 9c0 3.5 3 5.5 6 5.5-.39.49-.68 1.05-.85 1.65-.17.6-.22 1.23-.15 1.85v4" />
      <path d="M9 18c-4.51 2-5-2-7-2" />
    </svg>
  )
}


function LinkedinIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M16 8a6 6 0 0 1 6 6v7h-4v-7a2 2 0 0 0-2-2 2 2 0 0 0-2 2v7h-4v-7a6 6 0 0 1 6-6z" />
      <rect width="4" height="12" x="2" y="9" />
      <circle cx="4" cy="4" r="2" />
    </svg>
  )
}







