/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/EtYhLMAW0J8
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"
import { SVGProps } from "react";

export default function MainPage() {
  return (
    <div className="max-w-4xl mx-auto p-8">
      <header className="flex flex-col items-center mb-12">
        <h1 className="text-4xl font-bold">Ansub Khan</h1>
        <p className="text-lg">Engineer & Designer</p>
        <div className="flex space-x-4 mt-4">
          <XIcon className="h-6 w-6" />
          <HeadphonesIcon className="h-6 w-6" />
          <LinkedinIcon className="h-6 w-6" />
        </div>
      </header>
      <nav className="flex justify-center space-x-6 border-b pb-4 mb-8">
        <a className="text-sm font-semibold" href="#">
          About
        </a>
        <a className="text-sm font-semibold" href="#">
          Blogs
        </a>
        <a className="text-sm font-semibold" href="#">
          Uses
        </a>
        <a className="text-sm font-semibold" href="#">
          Newsletter
        </a>
        <a className="text-sm font-semibold" href="#">
          Contact
        </a>
      </nav>
      <main>
        <section className="mb-12">
          <p className="mb-8">
            Founding Software Engineer & Designer at Speedy (YC-W23). Passionate about crafting tools that empower
            developers and designers to express themselves seamlessly.
          </p>
          <h2 className="text-2xl font-semibold mb-4">Experience</h2>
          <div className="mb-6">
            <h3 className="font-semibold">
              Founding Software Engineer <span className="text-sm font-normal">(PRESENT)</span>
            </h3>
            <p>Speedybrand (YC-W23)</p>
          </div>
          <div className="mb-6">
            <h3 className="font-semibold">Front-End Engineer</h3>
            <p>Maya Labs (YC-S22)</p>
          </div>
        </section>
        <section className="mb-12">
          <h2 className="text-2xl font-semibold mb-4">Projects</h2>
          <div className="grid grid-cols-2 gap-4">
            <div className="mb-6">
              <BracketsIcon className="h-8 w-8 mb-2" />
              <h3 className="font-semibold">syntaxUI</h3>
              <p>Ready-to-use UI elements designed for rapid development.</p>
            </div>
            <div className="mb-6">
              <PocketIcon className="h-8 w-8 mb-2" />
              <h3 className="font-semibold">Prettyfolio</h3>
              <p>A curated collection of portfolios for inspiration.</p>
            </div>
            <div className="mb-6">
              <GlobeIcon className="h-8 w-8 mb-2" />
              <h3 className="font-semibold">Ansubkhan.com</h3>
              <p>My personal website, blogs and newsletter.</p>
            </div>
            <div className="mb-6">
              <QuoteIcon className="h-8 w-8 mb-2" />
              <h3 className="font-semibold">Quote Vault</h3>
              <p>Social media, but for sharing quotes.</p>
            </div>
            <div className="mb-6">
              <PaletteIcon className="h-8 w-8 mb-2" />
              <h3 className="font-semibold">Enchant</h3>
              <p>A vibrant theme for Visual Studio Code.</p>
            </div>
          </div>
        </section>
        <section className="mb-12">
          <h2 className="text-2xl font-semibold mb-4">Latest Blogs</h2>
          <div className="mb-4">
            <p className="mb-2">2024-03-31 Rejections don't define you</p>
            <p className="mb-2">2024-01-13 A Rollercoaster Ride with Arc</p>
          </div>
          <a className="text-sm font-semibold" href="#">
            Read More
          </a>
        </section>
        <section className="mb-12">
          <h2 className="text-2xl font-semibold mb-4">Luminary Newsletter</h2>
          <p className="mb-4">
            Stay ahead of the curve with my monthly newsletter called Luminary. Receive valuable insights on the latest
            trends, techniques, and tools in web development and design.
          </p>
          <form className="flex">
            <Input className="flex-1 mr-2" placeholder="Enter your email" type="email" />
            <Button>Subscribe</Button>
          </form>
        </section>
      </main>
      <footer className="text-center">
        <p>© 2024 - Ansub Khan</p>
      </footer>
    </div>
  )
}

function BracketsIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M16 3h3v18h-3" />
      <path d="M8 21H5V3h3" />
    </svg>
  );
}

function GlobeIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="12" cy="12" r="10" />
      <path d="M12 2a14.5 14.5 0 0 0 0 20 14.5 14.5 0 0 0 0-20" />
      <path d="M2 12h20" />
    </svg>
  );
}

function HeadphonesIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M3 14h3a2 2 0 0 1 2 2v3a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-7a9 9 0 0 1 18 0v7a2 2 0 0 1-2 2h-1a2 2 0 0 1-2-2v-3a2 2 0 0 1 2-2h3" />
    </svg>
  );
}

function LinkedinIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M16 8a6 6 0 0 1 6 6v7h-4v-7a2 2 0 0 0-2-2 2 2 0 0 0-2 2v7h-4v-7a6 6 0 0 1 6-6z" />
      <rect width="4" height="12" x="2" y="9" />
      <circle cx="4" cy="4" r="2" />
    </svg>
  );
}

function PaletteIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="13.5" cy="6.5" r=".5" fill="currentColor" />
      <circle cx="17.5" cy="10.5" r=".5" fill="currentColor" />
      <circle cx="8.5" cy="7.5" r=".5" fill="currentColor" />
      <circle cx="6.5" cy="12.5" r=".5" fill="currentColor" />
      <path d="M12 2C6.5 2 2 6.5 2 12s4.5 10 10 10c.926 0 1.648-.746 1.648-1.688 0-.437-.18-.835-.437-1.125-.29-.289-.438-.652-.438-1.125a1.64 1.64 0 0 1 1.668-1.668h1.996c3.051 0 5.555-2.503 5.555-5.554C21.965 6.012 17.461 2 12 2z" />
    </svg>
  );
}

function PocketIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M4 3h16a2 2 0 0 1 2 2v6a10 10 0 0 1-10 10A10 10 0 0 1 2 11V5a2 2 0 0 1 2-2z" />
      <polyline points="8 10 12 14 16 10" />
    </svg>
  );
}

function QuoteIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M3 21c3 0 7-1 7-8V5c0-1.25-.756-2.017-2-2H4c-1.25 0-2 .75-2 1.972V11c0 1.25.75 2 2 2 1 0 1 0 1 1v1c0 1-1 2-2 2s-1 .008-1 1.031V20c0 1 0 1 1 1z" />
      <path d="M15 21c3 0 7-1 7-8V5c0-1.25-.757-2.017-2-2h-4c-1.25 0-2 .75-2 1.972V11c0 1.25.75 2 2 2h.75c0 2.25.25 4-2.75 4v3c0 1 0 1 1 1z" />
    </svg>
  );
}

function XIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M18 6 6 18" />
      <path d="m6 6 12 12" />
    </svg>
  );
}
